apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # App of Apps Application
  - application.yaml

  # 각 앱의 ArgoCD Application 중앙 관리
  # PostgreSQL databases
  - postgresql-dev/argocd.yaml
  - postgresql/argocd/postgresql.yaml

  # Object storage
  - minio/argocd.yaml

  # Database management tools
  - pgweb/argocd.yaml
