apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-cnpg-daily-backup
  namespace: postgresql-cnpg
spec:
  # Daily backup at 2 AM KST (5 PM UTC previous day)
  schedule: "0 17 * * *"
  backupOwnerReference: self
  cluster:
    name: postgresql-cnpg
  method: barmanObjectStore
  immediate: true
