apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storage-class.yaml
- persistent-volumes.yaml
- vault/minio-root-password.yaml
- vault/minio-oidc-secret.yaml
- vault/minio-console-secret.yaml
- ingress.yaml
- console-deployment.yaml
